{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-16T09:52:27Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/lighthouse to version 1.6.18

      from: https://github.com/jenkins-x/go-scm.git
    sha: 6d04b99341e0183419f54d95d7a280e6e9553754
  gitHttpUrl: https://github.com/jenkins-x/lighthouse
  gitOwner: jenkins-x
  gitRepository: lighthouse
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/jenkins-x/lighthouse/releases/tag/v1.0.26
  version: 1.0.26
status: {}
 
{{- end }}
