{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-01T08:18:19Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/lighthouse to version 1.6.11

      from: https://github.com/jenkins-x/go-scm.git
    sha: 1a524555ebd324c8059aef1bd75687a09eef3b3c
  gitHttpUrl: https://github.com/jenkins-x/lighthouse
  gitOwner: jenkins-x
  gitRepository: lighthouse
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/jenkins-x/lighthouse/releases/tag/1.0.12
  version: 1.0.12
status: {}
 
{{- end }}
