{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-24T14:47:50Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: 64324ada51bc538040019a0a443566fde7d22328
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fmt
    sha: ae28dd044da46f7dabdee7c1d593c73ac09f6564
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: improve uses reuse

      so that we can reuse volumes, and stepTemplate resources like workingDir, resources and volumeMounts so that the call site tekton YAML can be much smaller
    sha: ce0b55fbe9eb6146f1a385406dcb66585af9f595
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: the release replace of versions

      to avoid changing the image names of the different deployments
    sha: 81f28cb0da7b42d315f46a84b5107b4cf0e5d841
  gitHttpUrl: https://github.com/jenkins-x/lighthouse
  gitOwner: jenkins-x
  gitRepository: lighthouse
  name: '{{ .Chart.Name }}'
  version: 1.0.4
status: {}
 
{{- end }}
